import { readdir, readFile, writeFile, stat } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const SKIP_DIRS = new Set([
  '.git',
  'node_modules',
  'scripts',
]);

function titleFromDir(name) {
  return name
    .split(/[-_]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

async function presentationTitle(dirPath, dirName) {
  const indexPath = join(dirPath, 'index.html');
  try {
    const html = await readFile(indexPath, 'utf8');
    const match = html.match(/<title[^>]*>([^<]+)<\/title>/i);
    if (match) {
      return match[1]
        .replace(/\s*[—–-]\s*.+$/, '')
        .trim();
    }
  } catch {
    // fall through
  }
  return titleFromDir(dirName);
}

async function countHtmlFiles(dirPath) {
  const entries = await readdir(dirPath, { withFileTypes: true });
  return entries.filter((e) => e.isFile() && e.name.endsWith('.html')).length;
}

export async function generateIndex() {
  const entries = await readdir(root, { withFileTypes: true });
  const presentations = [];

  for (const entry of entries) {
    if (!entry.isDirectory() || SKIP_DIRS.has(entry.name) || entry.name.startsWith('.')) {
      continue;
    }

    const dirPath = join(root, entry.name);
    const htmlCount = await countHtmlFiles(dirPath);
    if (htmlCount === 0) {
      continue;
    }

    presentations.push({
      slug: entry.name,
      title: await presentationTitle(dirPath, entry.name),
      htmlCount,
      href: `/${entry.name}/`,
    });
  }

  presentations.sort((a, b) => a.slug.localeCompare(b.slug));

  const cards = presentations.length
    ? presentations.map((p) => `    <a class="card" href="${p.href}">
      <div class="card-body">
        <h2>${escapeHtml(p.title)}</h2>
        <p class="slug">${escapeHtml(p.slug)}</p>
        <p class="meta">${p.htmlCount} HTML file${p.htmlCount === 1 ? '' : 's'}</p>
      </div>
    </a>`).join('\n')
    : `    <p class="empty">No presentations yet. Add a subdirectory with HTML files and run <code>npm run index</code>.</p>`;

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Presentations</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
:root{--bg:#0a0e14;--surface:#131920;--card:#1c2128;--border:#1e2a36;--text:#e6edf3;--muted:#7d8a97;--dim:#6e7681;--accent:#58a6ff}
body{background:var(--bg);color:var(--text);font:16px/1.7 -apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;min-height:100vh;padding:2.5rem 1.5rem}
a{color:var(--accent);text-decoration:none}
.wrap{max-width:760px;margin:0 auto}
.hero{text-align:center;padding:0 0 2.5rem}
.hero h1{font-size:2.2rem;font-weight:800;letter-spacing:-1px;margin-bottom:.4rem}
.hero p{color:var(--muted);font-size:1rem}
.card-list{display:flex;flex-direction:column;gap:1rem}
.card{display:block;background:var(--card);border:1px solid var(--border);border-radius:14px;padding:1.5rem 1.75rem;transition:border-color .2s,transform .15s,box-shadow .2s}
.card:hover{border-color:var(--accent);transform:translateY(-2px);box-shadow:0 8px 24px #58a6ff12}
.card-body h2{font-size:1.15rem;font-weight:700;margin-bottom:.25rem}
.card-body .slug{color:var(--dim);font-size:.82rem;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;margin-bottom:.35rem}
.card-body .meta{color:var(--muted);font-size:.85rem}
.empty{color:var(--muted);text-align:center;padding:2rem;background:var(--surface);border:1px dashed var(--border);border-radius:12px}
.empty code{background:var(--card);padding:.15rem .4rem;border-radius:4px;font-size:.85rem}
footer{text-align:center;padding:2rem 0 0;margin-top:2.5rem;border-top:1px solid var(--border);color:var(--dim);font-size:.8rem}
</style>
</head>
<body>
<div class="wrap">
  <div class="hero">
    <h1>Presentations</h1>
    <p>HTML slide decks and demo materials. Each folder is a self-contained presentation.</p>
  </div>
  <div class="card-list">
${cards}
  </div>
  <footer>Generated by <code>npm run index</code> · ${presentations.length} presentation${presentations.length === 1 ? '' : 's'}</footer>
</div>
</body>
</html>
`;

  await writeFile(join(root, 'index.html'), html);
  console.log(`Wrote index.html (${presentations.length} presentation${presentations.length === 1 ? '' : 's'})`);
}

function escapeHtml(value) {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  generateIndex().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
